server:
  port: 80
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
  ssl:
#    key-store: classpath:6452020_www.jiajialx.ink.jks
#    key-password: Bj5UG7sY
    key-store: classpath:6452020_www.jiajialx.ink.pfx
    key-store-password: bod73L9k
    key-store-type: PKCS12
    enabled: true


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/scenic_spot?useUnicode=true&characterEncodeing=UTF-8&useSSL=YES&serverTimezone=GMT
    username: root
    password: dtt000923
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  max-http-header-size: 102400


  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:Mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
